---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: technova-weather-app-run
  namespace: demo-project
spec:
  pipelineRef:
    name: technova-weather-app-tektontest
  params:
    - name: ARGOCD_SERVER
      value: openshift-gitops-server.openshift-gitops.svc:80
    - name: ARGOCD_USERNAME
      value: admin
    - name: ARGOCD_PASSWORD
      value: 4BxbuHDeyr8PpLT67IgRtQZVNqWkajv1
    - name: REPO_URL
      value: "https://github.com/ysoni-redhat/spring-rhdhtest1313.git"
    - name: DEST_NAMESPACE
      value: demo-project
    - name: DEST_SERVER
      value: "https://kubernetes.default.svc"
    - name: IMAGE_APP_PATH
      value: "deploy/k8s/image"
    - name: MAIN_APP_PATH
      value: "deploy/k8s/app"
  taskRunTemplate:
    serviceAccountName: pipeline
  workspaces:
    - name: output
      volumeClaimTemplate:
        metadata:
          name: git-clone-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
